### ISSUE TITLE
snakemake.exceptions.WorkflowError: Config file circos not found

### ISSUE THREAD

**Issue by guochangjiang** [thiesgehrmann/proteny#6]
$ proteny -t 10 example_config.json
snakemake --snakefile "/opt/Biosoft/proteny/Snakefile" --cores "10" --use-conda --conda-prefix "/opt/Biosoft/proteny/.snakemake/conda" --configfile "example_config.json"  circos
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/site-packages/snakemake/io.py", line 1564, in _load_configfile
    with open(configpath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'circos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/snakemake", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 2551, in main
    success = snakemake(
  File "/opt/anaconda3/lib/python3.8/site-packages/snakemake/__init__.py", line 503, in snakemake
    overwrite_config.update(load_configfile(f))
  File "/opt/anaconda3/lib/python3.8/site-packages/snakemake/io.py", line 1594, in load_configfile
    config = _load_configfile(configpath)
  File "/opt/anaconda3/lib/python3.8/site-packages/snakemake/io.py", line 1589, in _load_configfile
    raise WorkflowError("{} file {} not found.".format(filetype, configpath))
snakemake.exceptions.WorkflowError: Config file circos not found.

**Comment by RmmlAndReas** [comment]
Same issue for me!

**Comment by alambard** [comment]
same issue here too

**Comment by Romualdo22** [comment]
same issue!
